### ISSUE TITLE
Use of concurrency for speed improvement

### ISSUE THREAD

**Issue by cdecompilador** [IgaguriMK/cargo-clean-recursive#4]
I've used it a couple times but I've noticed that it calls the `cargo clean`s sequentially, maybe using [async-process](https://crates.io/crates/async-process) or just calling `.spawn()` on the `Command`s and setting a maximum childs could improve performance by a lot.

**Comment by IgaguriMK** [comment]
Added implementation to do directory scan and clean in parallel.

The existing implementation scanned directories sequentially, which resulted in a long processing time.
To improve this, we changed to an asynchronous implementation using tokio, and speeded up the process by scanning and cleaning the directory in parallel.

Closes #4
